version: "3.9"

services:
  postgres:
    container_name: pgsql-docker
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
      args:
        TIMEZONE: "${TIMEZONE}"
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    volumes:
      - pgsql-docker:/var/lib/postgresql/data
      - "./docker/postgres/configuration/postgresql.conf:/etc/postgresql.conf"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "${TIMEZONE}"
      PGTZ: "${TIMEZONE}"
      LC_ALL: "${POSTGRES_LC_ALL}"
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 80s

volumes:
  pgsql-docker:
    driver: local
